# M1 T01: Pràctica amb programació numèrica NumPy

## Tasca 1

- Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

- Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

- Exercici 3
Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.

- Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

# Exercici 1:

## Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [31]:
import numpy as np

def crea_array (arr):
    
    if arr.ndim != 1:
        print('Tu array :', arr, '--> no cumple con las especificaciones:')    
        print('Tiene las siguientes dimensiones:', int(arr.ndim))
        print('Tipo de contenido de tu array   :', arr.shape)
        print('Su contenido es                 :', arr.dtype)
    if arr.ndim == 1:
        print('Tu array :', arr, '--> SI cumple con las especificaciones:')      
        print('Tiene las siguientes dimensiones:', int(arr.ndim))
        print('Elementos del array             :', arr.size)
        print('Su contenido es                 :', arr.dtype)
        arr1 = arr.copy()  
        arr1.sort()      
        print('Valor Medio                     :', np.sum(arr1) / arr.shape)
        print('Valor Mean                      :', int(arr1.mean()))
        print('Min - Max                       :', arr1[0] , ' - ', arr1[-1])  
        print('Std Deviation                   :', int(np.std(arr1)))
        print('Array Original sin ordenar      :', arr)
        print('Array Original ordenado         :', arr1)
        
        


In [36]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
b = np.array([166, 266, 3666, 46, 56])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

crea_array(a)
print("----------------------------")
crea_array(b)
print("----------------------------")
crea_array(c)
print("----------------------------")
crea_array(d)
print("----------------------------")


Tu array : 42 --> no cumple con las especificaciones:
Tiene las siguientes dimensiones: 0
Tipo de contenido de tu array   : ()
Su contenido es                 : int32
----------------------------
Tu array : [ 166  266 3666   46   56] --> SI cumple con las especificaciones:
Tiene las siguientes dimensiones: 1
Elementos del array             : 5
Su contenido es                 : int32
Valor Medio                     : [840.]
Valor Mean                      : 840
Min - Max                       : 46  -  3666
Std Deviation                   : 1415
Array Original sin ordenar      : [ 166  266 3666   46   56]
Array Original ordenado         : [  46   56  166  266 3666]
----------------------------
Tu array : [[1 2 3]
 [4 5 6]] --> no cumple con las especificaciones:
Tiene las siguientes dimensiones: 2
Tipo de contenido de tu array   : (2, 3)
Su contenido es                 : int32
----------------------------
Tu array : [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] --> no cumple con las especi

# - Exercici 2

## Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.


In [60]:
import random
import numpy as np
from numpy import random

def crea_quadrat_n_x_n(n):
    
    x = random.randint(100, size=(n, n))
    return(x)

y=crea_quadrat_n_x_n(10)
print(y)

[[90 51 29 38 94  5 28 58 29 95]
 [ 3 54 67 86  4 44 13 14 13 13]
 [97 97 96 35 32 66 55 10 33 73]
 [12 83 82 19 82 21 31  8 29 92]
 [82 11 96 33 70 65 55  5  0 70]
 [36 66 80 68 96 71 41 10 88 79]
 [72 35 30 34  3 17 88 65 37 34]
 [91 41 32  3 30 99 60 67 64 94]
 [ 2 25 60 67 20 16 74 35 32 44]
 [70 77 14 50 93 14 34 41 16 44]]


# - Exercici 3

## Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna.


In [90]:
def calcular_total_fila_columna (matriu , checkvisualy):

    print('-----Matriz original-----')
    print(y)
    
    if checkvisualy :
        print('-----MAtriz Acumnulada por filas-----')
        print(y.cumsum(axis=1))
        
    print('-----Total por filas-----')
    print(np.transpose(np.sum(y, axis=1)).reshape(n,1))


    z = np.transpose(y)
    w = z.cumsum(axis=1)
    x = np.transpose(w)

    if checkvisualy :

        print('-----MAtriz Acumnulada por columnas-----')
        print(x)

    print('-----Total por columnas-----')
    print(np.transpose(np.sum(z, axis=1)).reshape(1,n))

print ('---primera matriz ejemplo')
n=10
y=crea_quadrat_n_x_n(n)
calcular_total_fila_columna (y, True )

print ('---segunda matriz ejemplo')
n=5
y=crea_quadrat_n_x_n(n)
calcular_total_fila_columna (y, False )


---primera matriz ejemplo
-----Matriz original-----
[[45 29 72  1 37 56 88 27 37 26]
 [25 65 98 98 50 90 66 44 33 56]
 [63 78 83 34 40 52 28 15 60  9]
 [34 64 29 91 18 89 71 11 32 95]
 [77 33 74 27 93 50 69 88 12 87]
 [80 62 84 65 45 47  4  8 32 85]
 [22 53 49 95 77 81 31 58 52  4]
 [62 72 89 32 89 20 61 27 44 98]
 [59  5 85 85 15 20 61 86 91 58]
 [ 8 12 19 28 73 77  7 66 74 71]]
-----MAtriz Acumnulada por filas-----
[[ 45  74 146 147 184 240 328 355 392 418]
 [ 25  90 188 286 336 426 492 536 569 625]
 [ 63 141 224 258 298 350 378 393 453 462]
 [ 34  98 127 218 236 325 396 407 439 534]
 [ 77 110 184 211 304 354 423 511 523 610]
 [ 80 142 226 291 336 383 387 395 427 512]
 [ 22  75 124 219 296 377 408 466 518 522]
 [ 62 134 223 255 344 364 425 452 496 594]
 [ 59  64 149 234 249 269 330 416 507 565]
 [  8  20  39  67 140 217 224 290 364 435]]
-----Total por filas-----
[[418]
 [625]
 [462]
 [534]
 [610]
 [512]
 [522]
 [594]
 [565]
 [435]]
-----MAtriz Acumnulada por columnas-----
[[ 45  29 

# - Exercici 4

## Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

In [98]:
def coeficiente_correlacion(matriz):
    R1 = np.corrcoef(matriz)
    return R1
    
n=5
y=crea_quadrat_n_x_n(n)
print('Matriiu de dades')
print(y)
print('')
print('Matriu de correlació')
print(coeficiente_correlacion(y))

Matriiu de dades
[[ 9 45 95 19 12]
 [56 79 39 35 45]
 [36 84 23 65 97]
 [ 5 49 99 98 63]
 [82 52 33 57 29]]

Matriu de correlació
[[ 1.         -0.06907674 -0.51046948  0.53024109 -0.47986819]
 [-0.06907674  1.          0.31502617 -0.60852327  0.2899194 ]
 [-0.51046948  0.31502617  1.         -0.02050838 -0.31466992]
 [ 0.53024109 -0.60852327 -0.02050838  1.         -0.67922975]
 [-0.47986819  0.2899194  -0.31466992 -0.67922975  1.        ]]
